server:
  port: 8765

spring:
  application:
    name: api-gateway
  profiles:
    active: eureka-server

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
