spring:
  application:
    name: storage
  config:
    import: optional:file:.env[.properties]
  datasource:
#    url: jdbc:postgresql://${HOST}:5432/${POSTGRES_DATABASE}?currentSchema=${POSTGRES_SCHEMA}
    url: jdbc:postgresql://localhost:5432/diesel_micro
#    username: ${POSTGRES_USERNAME}
    username: postgres
#    password: ${POSTGRES_PASSWORD}
    password: 123
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
#        show_sql: true
  liquibase:
    change-log: classpath:liquibase/db.changelog.yaml
    enabled: true
    default-schema: storage