spring:
  application:
    name: storage
  config:
    import: optional:file:storage/.env[.properties]
  profiles:
    active: eureka-server
  datasource:
    url: jdbc:postgresql://${HOST}:5432/${POSTGRES_DATABASE}?currentSchema=${POSTGRES_SCHEMA}
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  liquibase:
    change-log: classpath:liquibase/db.changelog.yaml
    enabled: true
    default-schema: storage
  kafka:
    bootstrap-servers: http://127.0.0.1:9092
logging:
  config: classpath:logback-spring.xml
server:
  port: 8081
springdoc:
  override-with-generic-response: false

